### ISSUE TITLE
Support Poetry- and Flit-style pyproject.toml instead of the setup.json

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida-registry#92]
People might want to use something else than `setuptools` to manage their projects.
There are currently two popular alternatives using solely `pyproject.toml`: Poetry and Flit.
Unfortunately `pyproject.toml` does not have a standard dependency, entrypoint or trove classifier spec, which makes it build-system dependent.

Example for Poetry (tested except for the plugin part):

```toml
[tool.poetry]
name = "aiida-graphql"
version = "0.0.1"
description = "Strawberry-based GraphQL API Server for AiiDA"
authors = ["Tiziano Müller <tiziano.mueller@chem.uzh.ch>"]
repository = "https://github.com/dev-zero/aiida-graphql"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Science/Research",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
aiida = "^1.0.0b6"
strawberry-graphql = "^0.16.5"

[tool.poetry.plugins."aiida.cmdline.data"]
"graphql-data" = "aiida_graphql.cli:some_data_cli_command"
```

Example for Flit (untested):

```toml
[tool.flit.metadata]
module = "aiida-graphql"
author = "Tiziano Müller"
author-email = "tiziano.mueller@chem.uzh.ch"
home-page = "https://github.com/dev-zero/aiida-graphql"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Science/Research",
]
description-file = "README.md"
requires =[
    "aiida >=1.0.0b6 <1.1.0",
    "strawberry-graphql >=0.16.5 <0.17"
]
requires-python = ">=3.7 <4"

[tool.flit.entrypoints."aiida.cmdline.data"]
"graphql-data" = "aiida_graphql.cli:some_data_cli_command"
```

What has to be implemented:

* [x] parse toml (using either `tomlkit` or `pytoml`) based on file-type (if url contains `pyproject.toml` use the toml parser, otherwise continue with loading it as json)
* [x] parse requirements to pull out AiiDA version, for Flit it seems that the current version parser could be partially reused, for Poetry it might be beneficial to use a semantic version parser instead
* [x] pulling out the entrypoints is the same for both, just with a different TOML list name
